### ISSUE TITLE
Generic array type support

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/nballerina-cpp#124]
**Description:**
Current implementation supports only int arrays at rust side. We need to support in a generic manner.

`int`, `string`, `float`, `boolean`, `array-of-arrays`, `union-type`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
#136 
#137

**Comment by ramakotareddy** [comment]
Hi All, i am planing to implement template function in rust side for generic data type for Array. Do you have any thoughts on this?
Please share your thoughts.

**Comment by ruvi-d** [comment]
> Hi All, i am planing to implement template function in rust side for generic data type for Array. Do you have any thoughts on this?
> Please share your thoughts.

Is it possible to call Rust template functions via a C ABI? 
As in can you expose a Rust generic function with our runtime lib(with the `#[no_mangle].. pub extern "C".. ` ) and call the functions from a C app? 
Better do a small experiment and see if you haven't already.

**Comment by ayonam** [comment]
@ruvi-d, yes, this is a good idea.  It didn't occur to me that exposing templates from Rust to C may not be trivial.  With no_mangle, it may actually be impossible.  What I would rather want to do is to change to a setup where we do not use no_mangle.  Instead we incorporate the name mangler from Rust into our compiler to generate mangled names using the same algorithm that Rust uses, so that the linker will always find the right symbols and things will work just fine.  If we go there, then we can use all the object oriented methodologies in Rust and expect to be able to call them from the LLVM generated code. 

I might be worthwhile to explore pulling out the name mangler from Rust and see how we can integrate it with the LLVM framework that we are using.
