### ISSUE TITLE
Removing random value causes infinite loop

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/nballerina-cpp#195]
**Description:**
https://github.com/ballerina-platform/nballerina/blob/47412e296861a2a4b8cee4cbd22e3753dc207852/compiler/codegen/TypeCastInsn.cpp#L114
In the above place, we are generating random value and store them. Then inside the package.cpp we replace that value with another value. Without using a random value, if we use constant value, codegen goes to infinite loop at this line. https://github.com/ballerina-platform/nballerina/blob/47412e296861a2a4b8cee4cbd22e3753dc207852/compiler/codegen/Package.cpp#L221

We need to find the reason for this.

**Comment by ayonam** [comment]
Okay.  The reason for this is that we are trying to replace all uses of that "value" with the offset we obtain from the string table.  If we use the same value everywhere, then for every entry that we pick from the string table, it will replace that offset at all the places where it has a use of that value.  Essentially, all the smart pointers will get the same offset every time we find a new offset from the string table.  This will become a never ending loop.  So we distinguish these using a random number.  A better approach could be to maintain a static variable somewhere that records the last number used and we use the next number after that. 

It is more like no two LLVM variables can have the same number.  So with constants in this case, since we are calling LLVMReplaceAllUsesWith().  So we are asking all the uses of this constant to be replaced.  Unless we intend to refer to the same constant, we must have unique constants.  

However, if for example we are going to have the same string being used in multiple places, then those places can use the same constant.  So we have to judiciously allocate a unique constant to each string that we add to the string table and use that constant at all the places.  

May be an additional map of the strings can be maintained for these unique constants and we can use that constant at every place where the same string is being used.  That way, the call to LLVMReplaceAllUsesWith() will have a better impact.  And this constant can be made unique by maintaining a static value somewhere which is incremented each time a new string is used that is not already in the map.

**Comment by KavinduZoysa** [comment]
@ayonam, thank you for your explaination. 

In method `LLVMReplaceAllUsesWith()`, All uses mean all the uses of the entire IR program?
