### ISSUE TITLE
Whole string table is passed to rust side

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/nballerina-cpp#217]
**Description:**
```
public function main() {
    any b = true;
    int i = <int>b;
}

```
Please consider the above example. To check the typecast we are passing the whole string table `__I__B\00` to the rust `is_same_type` function. I think it is not correct. We only need to pass the source type and destination type. In this case, we need to pass the type of i(`__I`) and inherent type of b(`__B`)

**Comment by KavinduZoysa** [comment]
@ayonam, FYI

**Comment by ayonam** [comment]
The string table should contain two strings, viz., __I and __B to denote the Integer and the Boolean.  So the string table should look like the following:
__I\00__B\00
If it is not, then the string table generation is incorrect.  If the string table is generated correctly, then you should be sending the two strings __I and __B separately.  As you can see, if you get the pointers to the beginning of the two strings, then they terminate at the next NULL characters (\00).  So you should not have any problem there.

Your problem lies in the generation of the string table.  The intermediate NULL characters are not being generated to terminate each string.

**Comment by KavinduZoysa** [comment]
Thank you @ayonam.
Yes, the problem is in string table generation.

**Comment by ruvi-d** [comment]
@KavinduZoysa : I didn't notice such strings like `__I__B\00` when I was test the PR for type strings. Is this issue on master and/or is it specific to Windows?

**Comment by KavinduZoysa** [comment]
This is on master. Let me check it again and update this issue.

**Comment by KavinduZoysa** [comment]
This issue appears in master branch, we need to fix
